Fix: Prevent loop in local watchdog plugin
When the local watchdog (LWD) expires a task, the LWD plugin `20_sysinfo`
goes into an infinite loop since the directory `/mnt/testarea` is not
created for the non-rhts restraint package. An error returned by `diff`
utility within an infinite loop was not anticipated.  The fix
terminates the infinite loop when diff returns error.

Bug: 1813935

diff --git a/plugins/localwatchdog.d/20_sysinfo b/plugins/localwatchdog.d/20_sysinfo
--- a/plugins/localwatchdog.d/20_sysinfo
+++ b/plugins/localwatchdog.d/20_sysinfo
@@ -25,11 +25,11 @@ function WatchFile ()
         fi
         diff=$(diff -q $FILE $TMPFILE)
         rc=$?
-        if [ $rc != 0 ]; then
+        if [ $rc == 1 ]; then
             cat $FILE > $TMPFILE
         else
             rm $TMPFILE
-            return 0
+            return $rc
         fi
         sleep 2
     done
@@ -43,8 +43,12 @@ function SysRq ()
     echo $ACTION > /proc/sysrq-trigger
     # Wait until logfile has changed.
     WatchFile $LOGFILE
+    if [[ $? -ne 0 ]]; then
+        logger -p local2.warning -t "List of $ACTION Tasks" Check on $LOGFILE failed
+    fi
 
     logger -p local2.info -t "List of $ACTION Tasks" Stop
+
 }
 
 # Verbose tree view of running processes:
